## Numpy Practice (0.5 point)

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [1]:
#1
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x  


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [12]:
#2
y = np.arange(5)
np.tile(y, (5, 1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [17]:
#3
z = np.array([[0,1],[1,0]])
np.tile(z, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [23]:
#4
x = np.arange(10)
x[x%2!=0]

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix that follows the Gaussian distribution N(4,3).(Z-Score Normalization零均值归一化)

In [24]:
#5
arrays = np.random.normal(4,3,(5, 5))
(arrays-arrays.mean())/arrays.std()

array([[-0.10126418, -0.38270259,  0.68726739, -0.78173785,  0.18751437],
       [ 0.0577948 ,  1.25665804,  0.68936144,  1.0790401 ,  1.97964307],
       [-0.16097475, -2.08936519, -1.24641713,  0.05352793,  0.76542715],
       [ 1.52145804,  0.94711723, -0.68875679,  0.26060789, -1.2505112 ],
       [ 0.95860226, -0.94787337, -0.49265999, -1.04395448, -1.25780219]])

6. Consider a random positive 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [ ]:
#6

X = np.array([0.48660129, 0.64067014, 0.93301119, 0.55328471, 0.2628861, 
              0.18080466, 0.28289352, 0.99464788, 0.42403243, 0.49718628])

Y = np.array([0.46385448, 0.97130751, 0.4472571, 0.78994386, 0.56000864, 
              0.77150557, 0.6863419, 0.88128735, 0.5663552, 0.31280192])
print("X,Y:\n",X,Y)

R = np.sqrt(X**2 + Y**2)
T= np.arctan2(Y, X)

print("R:\n",R)
print("T:\n",T)


X, Y:
 [0.48660129 0.64067014 0.93301119 0.55328471 0.2628861  0.18080466
 0.28289352 0.99464788 0.42403243 0.49718628] [0.46385448 0.97130751 0.4472571  0.78994386 0.56000864 0.77150557
 0.6863419  0.88128735 0.5663552  0.31280192]
R:
 [0.67226616 1.16357059 1.03467328 0.9644352  0.61864269 0.79240846
 0.74235702 1.32890624 0.70750386 0.5874004 ]
T:
 [0.7614702  0.98770508 0.4470074  0.95979514 1.13190059 1.34059758
 1.17983784 0.72504275 0.92812514 0.56157395]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [7]:
#7
x=np.array([1,2,3,4,5])
y=np.zeros(len(x)+3*(len(x)-1),dtype=int)
y[::4]=x
print(y)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 

hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2)

First guess a result, then print the result, and finally find why

In [15]:
3*0.1

0.30000000000000004

In [ ]:
#8
print(np.nan * 0)  # 无*任何数都是无

print(np.nan == np.nan)  # 无和无不相等

print(np.inf > np.nan)  # 无不等于任何值，包括自己

print(np.nan - np.nan)  # 无-无仍是无

print(np.nan in set([np.nan]))  # 无在包含无的集合中，同一个内存对象

print(0.3 == 3 * 0.1) # 3*0.1精度问题

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [ ]:
#9
print(np.array(0) / np.array(0))  # 0/0未定义

print(np.array(0) // np.array(0))  # 整除

print(np.array([np.nan]).astype(int).astype(float))  # nan转成int会变成最小整数，再转回去已丢失nan信息

nan
0
[-9.22337204e+18]


C:\Users\zhu\AppData\Local\Temp\ipykernel_1892\2249945874.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))  # 0/0未定义
C:\Users\zhu\AppData\Local\Temp\ipykernel_1892\2249945874.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\zhu\AppData\Local\Temp\ipykernel_1892\2249945874.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
